// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwnuimseszcgdabjsdqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3bnVpbXNlc3pjZ2RhYmpzZHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjI2MjIsImV4cCI6MjA1NjEzODYyMn0.Y3LyIeIIHDEbjTi37iQFRTm7C8eyW8BSLVrQH7B4AwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);